### ISSUE TITLE
Incorrect bundling

### ISSUE THREAD

**Issue by Kimbo0o** [nikku/feelin#23]
__Describe the Bug__

The package.json file specifies `"type": "module"`, but entry point uses commonjs (require Syntax).
This causes errors when you try to test with vitest, see also: https://github.com/vitest-dev/vitest/issues/4007#issuecomment-1691096627

__Steps to Reproduce__

1. Take a look at type definition in `package.json`
2. See wrong Syntax in `index.json` https://www.npmjs.com/package/feelin?activeTab=code

__Expected Behavior__

The package.json should state `"type": "commonjs"` or the `index.json` file should be ESM Syntax.
See also: https://nodejs.org/api/packages.html 

__Environment__

- Library version: 1.0.0

**Comment by sheremet-va** [comment]
> The package.json should state `"type": "commonjs"` or the `index.json` file should be ESM Syntax

Adding `exports` field to `package.json` with the correct entry points might also help. And don't forget to use different extensions for CJS/ESM.

**Comment by nikku** [comment]
Sounds great. We want to use `cjs` for CommonJS files.

Happy to take a contribution that fixes this.
