### ISSUE TITLE
A list nested in a list with too many tokens cannot be evaluated

### ISSUE THREAD

**Issue by till-stadtler** [nikku/feelin#33]
__Describe the Bug__

The following expression throws an error:
```
[[substring before(string(now()), "@"),
  substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@")]]
```
"Property \<source\> is not a valid FEEL expression"

This expression is interpreted to be a list nested in an interval. The evaluation of this expression fails. 
When adding "..1" as the "rest" of the interval, the expression is deemed valid again: 
```
[[substring before(string(now()), "@"),
  substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@")]..1]
```

Removing entries from the nested list (reducing the complexity, the number of tokens) leads to a successful evaluation as a list nested in a list:
```
[[substring before(string(now()), "@"),
  substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@"),
 substring before(string(now()), "@")]]
```

__Steps to Reproduce__

1. copy the expressions above into a FEEL editor with the latest FEEL-JS engine

__Expected Behavior__

I expect the list nested in a list to always be interpreted as such, independent of the complexity of its entries. 

__Environment__

Desktop Modeler 5.16.0, Web Modeler (8.3?) or https://nikku.github.io/feel-playground

**Comment by nikku** [comment]
[Further nesting](https://nikku.github.io/feel-playground/?e=%7E3YCAkIB0gICAgICAgICtaP4El%2B2dSqs7qov35uWnlcYz0Yc9k0hkHibwoGwcKGsTxUgh%2F%2B4PtLZMs64V3zNYf7UlyX9%2FLBWAgA%3D%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true) will still cause a parse error. But let's see if a user detects that :see_no_evil:.

**Comment by nikku** [comment]
Fully addressed via https://github.com/nikku/feelin/commit/a775a124de7ba0608c181d45f38227b5ae8001bd.
