### ISSUE TITLE
evaluate returns wrown result for expression and context

### ISSUE THREAD

**Issue by ekzobrain** [nikku/feelin#66]
### Describe the Bug

```javascript
evaluate("string", {}) // return function()
```
while "string" is determined as a VariableName by the parser

### Steps to Reproduce

execute provided example

### Expected Behavior

returns `null`

### Environment

- Host (Browser/Node version), if applicable: Firefox latest
- OS: MacOS
- Library version: 3.0.1

**Comment by nikku** [comment]
@ekzobrain Thanks for reporting this issue. `string` is a built-in function. Why do you expect it to be `null`?

The following for example is valid in FEEL, asking if `string` is a function returning `string` type: 

```
string instance of function<> -> string
```

**Comment by ekzobrain** [comment]
But this works: https://nikku.github.io/feel-playground/?e=string&c=%7B%0A++%22string%22%3A+%22aa%22%0A%7D&t=expression&st=true

And syntax tree reports this expression as VariableName. In fact current behavior deffers depending on context. Is this correct?

**Comment by nikku** [comment]
Exactly. DMN FEEL is _context sensitive_. [This works, too](https://nikku.github.io/feel-playground/?e=if+foo+then+bar&c=%7B%0A++%22if+foo+then+bar%22%3A+true%0A%7D&t=expression&st=true).

**Comment by nikku** [comment]
What you're essentially doing is _shadowing_ a built-in.
