### ISSUE TITLE
Does evaluate() cache a parsed expression?

### ISSUE THREAD

**Issue by ekzobrain** [nikku/feelin#67]
I execute expressions with evaluate() in a loop with up to a thousand iterations.
Usually template or epression languages have separate parse and evaluate methods, the first is needs to execute only once, and the second only evaluated already parse epression with current context (variables).
Is this possible with `feelin` or does it persorm any internal AST cahing per expression?

**Comment by nikku** [comment]
DMN FEEL is _context sensitive_. I stressed earlier how this leads to [_interesting effects_](https://github.com/nikku/feelin/issues/66#issuecomment-1973878061).

You [_can_ cache executions](https://github.com/nikku/feelin/blob/main/src/interpreter.ts#L183), but will run into trouble if the context (any input data) changes.

**Comment by ekzobrain** [comment]
Interpreter is not exported, so I cannot use it directly. May you also export it? I need to cache prepared execution trees because I need to render compatible (by structure) context multiple times...

**Comment by nikku** [comment]
How do you enforce an equal structure?

**Comment by ekzobrain** [comment]
I use FEEL to render items (values and labels) in dynamic select form fields. So I have a FEEL expression for `label` and an expression for `value`.
Context is like this:
```js
options = [
  { name: "xxx", code: "yyy", "other": "zzz" },
  // repeated 100 times, for example
]
```

So I would like to compile expressing only once for `label` and for `value` and then render is for all 100 options. I am sure that all options have the same structure.
