### ISSUE TITLE
Context overrides should not override functions?

### ISSUE THREAD

**Issue by Skaiir** [nikku/feelin#72]
### Describe the Bug

This is a follow-up to https://github.com/nikku/feelin/issues/62.

Uncertain if this is 100% a bug, but see: https://nikku.github.io/feel-playground/?e=sum%28%5B1%2C2%5D%29&c=%7B%0A++%22sum%22+%3A+20%0A%7D%0A&t=expression&st=true.

Basically, context variables are overriding base functions now following the change we made to allow variables like "date" to be used, but this causes unexpected behaviors for a lot of people in forms who define variables like `sum`, which basically stops the sum function from working. I'm wondering where we should go with this.

### Steps to Reproduce

1. See attached playground link

### Expected Behavior

Uncertain at the moment, @nikku what do you think?

**Comment by Skaiir** [comment]
Camunda internal conversation that lead to discovery [here](https://camunda.slack.com/archives/C043W5V88M7/p1714464289616089?thread_ts=1714408842.090159&cid=C043W5V88M7).

**Comment by nikku** [comment]
My assessment is: Context overrides _absolutely_ override built-in variables. 

This is what we call _shadowing_ and if we'd want to prevent it, then we have to warn users about their unintentional override.

**Comment by nikku** [comment]
Closing this. FEEL as defined in the spec is _context sensitive_.
