### ISSUE TITLE
 in clause parsing and interpretation issue

### ISSUE THREAD

**Issue by spearsandshields** [nikku/feelin#74]
### Describe the Bug
if you try to run 
`3 in [1,2] or true` 
in feelin playground. It results in false. 

### Steps to Reproduce

1.visit link 
https://nikku.github.io/feel-playground/?e=3+in+%5B1%2C2%5D+or+true&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true

### Expected Behavior

I think this is due to the parser not able to determine the proper ending of an unary test when "in" is involved in a comparison.
The disjunction in the above case should involve `3 in [1,2]` and `true`
not `[1,2]` and `true`

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: Windows 10
- Library version: latest

**Comment by nikku** [comment]
@spearsandshields The specification backs up your claim. `disjunction` has higher precendence, than `comparison`, hence your expression should evaluate as follows: `(3 in [1,2]) or (true)`.

---

Relevant excerpts from the specification:

![image](https://github.com/user-attachments/assets/9814e263-a047-4e7c-aab8-832e4dbb7949)

![image](https://github.com/user-attachments/assets/a20ef76e-b75e-4553-b8b6-c27ef1ed0140)

**Comment by nikku** [comment]
Cf. [feelin playground](https://nikku.github.io/feel-playground/?e=%7E3YCAkIDbgICAgICAgIC9AgCX24Yxxmn1yIvRR71QexmvPbu9gtvDUftn5HH5DEhxe0PW3GUjcd8XgwsWMU7WLbg6tjSGGzvvf3mPIIA%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true) and [feel scala](https://camunda.github.io/feel-scala/docs/playground/?expression=ewogIGE6ICgyIGluIFsxLDJdKSBvciBmYWxzZSwKICBiOiAyIGluIChbMSwyXSBvciBmYWxzZSksCiAgcmVzdWx0OiAoMiBpbiBbMSwyXSBvciBmYWxzZSkKfQ%3D%3D&context=ewogICJ4IjogNQp9&expression-type=expression) playground. 

The two implementations handle the example structurally similar, with different interpretation around _null_ conversion. As we're also not directly comparing `disjunction` and `comparison` here, but nesting I suspect that such a statement will be (1) generally parsed this way (also we parse left to right) and (2) you're better off to disambiguate anyway.

----

As always, happy to take any _reasonable_ arguments and contribution to move this forward, i.e. a [dmn-tck](https://github.com/dmn-tck/tck) test case could ensure we end up in the right interpretation.

It won't be worth my time though, hence I'm closing this issue as won't fix.

**Comment by spearsandshields** [comment]
Sounds reasonable as per your priority, thanks for the investigation
