### ISSUE TITLE
Decimal cast rounding behaves incorrectly

### ISSUE THREAD

**Issue by Skaiir** [nikku/feelin#77]
### Describe the Bug

When casting a number to decimal with a fixed set decimals, [several issues can be observed](https://nikku.github.io/feel-playground/?e=%7E3YCAkIBAgICAgICAgIC9AgCXnKkNRzxkGtTV3JcpokEWAkLQ6ZCJm6GmNrg7v3woGKNybfr3MVGrcRRKkIYbCY2apcsSKtoqFJVG8Ab02ZqY0%2Bkmo5tc%2BC4tNFz%2Ff17GwIA%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true).

- Negative numbers ALWAYS round up, even in extreme cases like `-5.5999999999 `-> `-5.5`
- Both negative and positive numbers round towards zero when it's ambiguous, which is the opposite behavior from zeebe, which favors rounding towards the nearest even `0.5` -> `0`, and `-1.5` -> `-2`, which is also what the DMN spec defines.

### Steps to Reproduce

See the [playground example](https://nikku.github.io/feel-playground/?e=%7E3YCAkIBAgICAgICAgIC9AgCXnKkNRzxkGtTV3JcpokEWAkLQ6ZCJm6GmNrg7v3woGKNybfr3MVGrcRRKkIYbCY2apcsSKtoqFJVG8Ab02ZqY0%2Bkmo5tc%2BC4tNFz%2Ff17GwIA%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true) for evaluations

### Expected Behavior

The rounding behavior should be consistent with the zeebe feel engine.

**Comment by Skaiir** [comment]
For some reason I can't assign myself to issues here but consider me working on it.

**Comment by nikku** [comment]
> ### Expected Behavior 
>
> The rounding behavior should be consistent with the zeebe feel engine.

Please argue with the [DMN specification](https://www.omg.org/dmn/) to backup bug reports; I don't want to improve things to work like _another_ FEEL interpreter, but to be better aligned with the DMN specification.

**Comment by nikku** [comment]
I see that a respective note was [already part of the test suite](https://github.com/nikku/feelin/pull/78/commits/3ea54a208a3b4ebe20fa2aa03edcbf986074edd9#diff-6d44ea188256282642935f6999026b86f97f5743ee00219d3e4f3cc86b88ef4b); so I assume this improvement aligns with the specification, too.

**Comment by Skaiir** [comment]
@nikku You're right, I realized this at some point after creating the issue. But yeah either way the DMN spec and FEEL-Scala are already aligned on this.

**Comment by nikku** [comment]
This is released with [v3.1.1](https://github.com/nikku/feelin/releases/tag/v3.1.1).
