### ISSUE TITLE
Builtin `get value` does not seem to work for multiple levels of nesting

### ISSUE THREAD

**Issue by Skaiir** [nikku/feelin#80]
### Describe the Bug

When using `get value` with multiple levels of nesting, it seems to return null only. 

https://nikku.github.io/feel-playground/?e=%7E3YCAkIDYgICAgICAgIC9AgCX24YxznRFP3RPq6DFHT4vI0Y1o85xWXLyy17%2FNzCq2kULoyR5YKvp7fJylYqZ6aBbXAhoddJgbPYci3%2BdZYCA&c=%7B%7D&t=expression&st=true

### Steps to Reproduce

1. Check out the playground

### Expected Behavior

`get value({x:1, y: {z:0}}, ["y", "z"])` should resolve to 0, but currently resolves to null

**Comment by Skaiir** [comment]
As per the previous issue, please consider me assigned on this one.

**Comment by nikku** [comment]
You claim a particular expected behavior, but how is that backed by [the specification](https://www.omg.org/spec/DMN/1.5/Beta1/PDF)?

![image](https://github.com/user-attachments/assets/a3adbc22-b7ce-4668-af71-1ae3671ee355)

**Comment by Skaiir** [comment]
Aaah you're right! It's a camunda extension, not vanilla feelin. I understand where the confusion comes from. 

https://camunda.slack.com/archives/C0693F1NFK5/p1723793719886609

**Comment by nikku** [comment]
As this is a custom vendor extension I close this as won't fix.

**Comment by nikku** [comment]
I track such requests now using the `vendor extension` label.
